[package]
name = "parsnip"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "parsenip"
path = "src/bin/main.rs"

[lib]
name = "parsenip"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
